band_blurb = ['Unique in their genre, %s are back.',
              '%s always had a cult following.',
              'We thought we would never see %s again.',
              'After a prolonged hiatus, %s releases their new album.',
              'The true masters of ecletic indie, %s, are back with their fourth album this year.',
              'Surprising no one, %s finally release their debut album.',
              'Masters of live performance %s release their new single.',
              'Last year, %s were being hailed as the next big thing',
              'The chip tunes of %s are unsurpassed.', f'No one does it like %s',
              'Pioneers of ambient majestry mixed with deer sounds, %s has arrived!',
              'The last true rockers from the South Side of West Lisbon, %s, are back.',
              'Blips and blops and sound that rocks is the motto for %s.',
              'More influential than Jean Chalopin to an European kid in the Eighties, %s are back.',
              '%s are to Nollywood-style math rock techno what Melvins are to drone music.',
              'It is easier to overcome the Greenwald Density limit in a tokamak than it is to discuss Indie rock without mentioning %s',
              'The career of %s is as consistent as the Cosmic Microwave Background radiation measurements.',
              'Arithmetic prophets of the G string, %s are back on the scene.',
              'Can anyone be louder than %s?',
              'More prolific than James Last, %s show us their new work.',
              'Despite the problems with their frontperson, %s finally present their new release!',
              'Leftfield, Fluke, %s: Pioneers of Electronica.',
              'The pirate-rock crowd was taken by surprise when %s announed they were back on the studio last year.',
              'Lo-Fi sensations %s produce another album you can use to chill and study.',
              'The new release of %s may not appeal to busy internet nerds.','Beep %s boop!']
