band_blurb = ['Unique in their genre, %s are back.',
      '%s always had a cult following.',
      'We thought we would never see %s again.',
      'After a prolonged hiatus, %s releases their new album.',
      'The true masters of ecletic indie, %s, are back with their fourth album this year.',
      'Surprising no one, %s finally release their debut album',
      'Masters of live performance %s release their new single.',
      'Last year, %s were being hailed as the next big thing',
      'The chip tunes of %s are unsurpassed.', f'No one does it like %s',
      'Pioneers of ambient majestry mixed with deer sounds, %s has arrived!', 
      'The last true rockers from the South Side of West Lisbon, %s, are back.',
      'Blips and blops and sound that rocks is the motto for %s.']